# Generated by Django 4.1 on 2022-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.CharField(max_length=15, verbose_name='Важность')),
                ('accepted', models.BooleanField(verbose_name='Принято')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
