# Generated by Django 4.1 on 2022-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notes_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публично'),
        ),
    ]
