# Generated by Django 4.1 on 2022-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notes_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='priority',
            field=models.CharField(choices=[('3', 'Очень важно'), ('2', 'Важно'), ('1', 'Не важно')], max_length=15, verbose_name='Важность'),
        ),
    ]
