# Generated by Django 4.1 on 2022-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='accepted',
        ),
        migrations.AddField(
            model_name='notes',
            name='worker',
            field=models.CharField(blank=True, max_length=15, verbose_name='Исполнитель'),
        ),
    ]
