# Generated by Django 4.1 on 2022-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_notes_accepted_notes_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
