# Generated by Django 4.1 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_notes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
