# Generated by Django 4.1 on 2022-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notes_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='completed',
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(blank=True, default='Ожидает исполнителя', max_length=20, verbose_name='Выполнено'),
        ),
    ]
