# Generated by Django 4.1 on 2022-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_notes_completed_notes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(blank=True, default='Ожидает исполнителя', max_length=50, verbose_name='Выполнено'),
        ),
    ]
