# Generated by Django 4.1 on 2022-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_notes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='creator',
            field=models.CharField(default='ansys', max_length=15, verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
