# Generated by Django 4.1.4 on 2023-01-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_groups_user_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='UserGroup',
        ),
    ]
