# Generated by Django 4.1 on 2023-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_groups_delete_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15, verbose_name='Название группы')),
                ('group_password', models.CharField(blank=True, max_length=30, verbose_name='Пароль группы')),
            ],
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
