# Generated by Django 4.1 on 2023-01-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_group_delete_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('group', models.IntegerField(blank=True, verbose_name='Группа пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
