# Generated by Django 4.1 on 2023-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Группа пользователя'),
        ),
    ]
