# Generated by Django 4.1 on 2023-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='Пользователь', max_length=13, verbose_name='Должность'),
        ),
    ]
