# Generated by Django 4.1 on 2023-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust_factor',
            field=models.IntegerField(default=50, verbose_name='Уровень доверия'),
        ),
    ]
