# Generated by Django 4.1 on 2023-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Группа пользователя'),
        ),
    ]
