# Generated by Django 4.1 on 2023-03-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(blank=True, default='1', max_length=50, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='worker',
            field=models.CharField(blank=True, default='Нет', max_length=15, verbose_name='Исполнитель'),
        ),
    ]
