# Generated by Django 4.1 on 2023-03-31 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0028_profile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(default='forest', max_length=20, verbose_name='Тема')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
