# Generated by Django 4.1 on 2023-03-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_setting_remove_profile_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
