# Generated by Django 4.1 on 2023-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта')),
                ('password', models.CharField(blank=True, max_length=30, verbose_name='Пароль')),
            ],
        ),
    ]
