# Generated by Django 4.1 on 2023-05-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_userchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchange',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
