# Generated by Django 4.1 on 2023-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_userchange_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1, max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='userchange',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Эл. почта'),
        ),
    ]
