# Generated by Django 4.1 on 2023-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_profile_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
    ]
